config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, :only => [:show]

  root to: 'welcome#index'

  resources :listings do
    post :add_bookmark 
    delete :del_bookmark 
    get :basic
  end
  resources :images
  resources :vendors
  resources :charts


end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :user
  belongs_to :listing
  validates :listing_id, uniqueness: true 
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :listing
  has_attached_file :image, :styles => { :large =>"500x500>", :medium => "300x300>", :thumb => "100x100>" } 
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }

end

app/models/listing.rb
# require 'elasticsearch/model'

class Listing < ActiveRecord::Base

  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks


  searchkick synonyms: [["kitsilano", "kits"], ["avenue", "ave", "av", "ave.", "av."],\
   ["street", "str", "st", "st."], ["drive", "dr", "dr."], ["road", "rd", "rd."], ["boulevard", "blvd", "boul"],\
    ["court", "crt"], ["square", "sqr"], ["crescent", "cres", "crsent"], ["crossing", "xing"], ["alley", "ally"], \
    ["annex", "anex"], ["lane", "ln"], ["parkway", "pkwy", "pky"], ["place", "pl"], ["terrace", "terr"], \
    ["valley", "vally", "vlly"], ["way", "wy"], ["east", "e"], ["west", "w"]]

  belongs_to :user
  belongs_to :neighbourhood
  has_many :images
 
  def search_data
    {
      address: address,
      neighbourhood: neighbourhood.name,
      bedrooms: bedrooms,
      bathrooms: bathrooms,
      price: price,
      home_type: home_type
    }
  end

end



# Listing.import # This ensures that new users will be auto-indexed.

app/models/neighbourhood.rb
class Neighbourhood < ActiveRecord::Base
  has_many :listings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  validates :password, :presence => true,
                     :on => :create,
                     :format => {:with => /\A.*(?=.{8,})(?=.*\d)(?=.*[a-z]).*\Z/ }

  validates :email, :presence => true,
            :uniqueness =>true,
            :format => {:with => /.+@.+\..+/i}
            
  has_many :listings
  has_many :bookmarks

  has_many :bookmarked_listings, through: :bookmarks, source: :listing

  def self.new_guest
    new { |u| u.guest = true }
  end
  
  def name
    guest ? "Guest" : firstname
  end
  
  def move_to(user)
    tasks.update_all(user_id: user.id)
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def index
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      render json: { message: "success", fileID: @image.id }, status: 200
    else
      render json: { error: @image.errors.full_messages.join(',')}, status: 400
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy 
    redirect_to :back
  end


  private
  def image_params
    params.require(:image).permit(:image, :listing_id)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy] 

  def index
    if params[:query]
      @listings = Listing.search(params[:query] + "*", misspellings: {edit_distance: false}, where: params[:query_options].deep_symbolize_keys)
    else
      @listings = Listing.page(params[:page]).per(12).order(created_at: :desc)
    end
  end

  def show
 
  end

  def add_bookmark
    @bookmark = Bookmark.new user_id: current_user.id, listing_id: params[:listing_id]
    if @bookmark.save
      render json: @bookmark.as_json(include: :listing)
    end
  end

  def del_bookmark
    Bookmark.find_by(user_id: current_user.id, listing_id: params[:listing_id]).destroy
    render nothing: true
  end

  def new
    @listing = current_user.listings.build
  end

  def create
    @listing = current_user.listings.build(listing_params)
    if @listing.save
      redirect_to @listing, notice: 'Listing was successfully entered.'
    else
      render action: 'new'
    end
  end

  def edit 

  end

  def update
    if @listing.update(listing_params)
    redirect_to @listing, notice: "Your Listing was successfully updated."
    else
      render :edit      
    end
  end

  def destroy
    @listing.destroy
    redirect_to action: "index"
  end

  def basic
    @listing = Listing.find(params[:listing_id])
  end

  def details
    @listing = Listing.new
  end

  def amenities
    @listing = Listing.new
  end

  def photos
    @listing = Listing.new
  end

  private

  def set_listing
    @listing = Listing.find(params[:id])
  end

  def correct_user
    @listing = current_user.listings.find_by(id: params[:id])
    redirect_to listings_path, notice: "Not authorized to edit this listing" if @listing.nil?
  end

  def listing_params
    params.require(:listing).permit(
      :address, :unit_number, :street_name, :city, :postal_code, :price, :bedrooms, :bathrooms, :size, :year_built, :home_type, :type_ownership, :levels, :full_bathrooms, :half_bathrooms, :fireplaces, :taxes, :strata_fees, :lot_size, :walkscore, :property_summary, :features_description, :parking, :storage, :basement, :bike_room, :elevator, :garden, :insuite_laundry, :garage, :doorman, :gym, :amenities_room, :air_conditioning, :washer, :dishwasher, :stove, :fridge, :hot_tub, :pool, :pet_friendly, :wheelchair_accessible, :neighbourhood_id, :dryer, :image
      )

  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:firstname, :lastname, :email, :password, :password_confirmation, :current_password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
 
  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def edit
  end

  # Allows user to make a guest account
  # Move Guest data into actual user once signed up
  def create
    @user = params[:user] ? User.new(params[:user]) : User.new_guest
    if @user.save
      current_user.move_to(@user) if current_user && current_user.guest?
      session[:user_id] = @user.id
      redirect_to root_url
    else
      render "new"
    end
  end

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def human_boolean(boolean)
    boolean ? 'Yes' : ' '
  end

  def to_currency(number)
    number.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
  end

end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper 

  def type_ownership
    ["Freehold Strata", "Freehold NonStrata", "Leasehold Prepaid-Strata", "Cooperative Ownership"]
  end

  def type_property
    ["Condo", "House", "Townhouse"]
  end
  
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-wrap">
  <div class="footer" id="footer-id">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 footer-grid-pad"> 
      <ul class="footer-nav-ul">
        <li><a href="/">Home</a></li>
        <li><a href="/#choose-us">Why us?</a></li>
        <li><a href="/#feature-listing">Featured Listings</a></li>
        <li><%= link_to "Vendors", vendors_path %></li>
      </ul>

      <a href="/listings" class="listings-footer-btn">View Listings</a>
      <br>
      <br>
      <br>
      <hr class="footer-hr">
      <br>
      <div class="footer-p-wrap">
        <p class="footer-p">© 2016 Unlisted. All rights reserved.</p>
        <p class="footer-p2"><em>The information and services offered on this website are provided with the understanding that all information is fabricated for demonstration purposes.<br>All listings are sample data, and are not representative of actual market conditions. </em></p>
      </div>
    </div> 
  </div>
  </div>
  </div> 
</footer>

app/views/layouts/_header.html.erb
<section class="overlay nav navbar">

<%= image_tag "unlisted-logo.png", class: "nav-logo" %>
  <p class="icon">&#9776;</p>
  <div class="navbar-collapse collapse navbar-right">
    <ul class="nav navbar-nav">

      <li class="dropdown">
       <a href="#" class="dropdown-toggle" data-toggle="dropdown" roll="button"aria-haspopup="true" aria-expanded="false">Home <span class="caret"></span></a>        
        <ul class="dropdown-menu">
          <li><a href="/">Home</a></li>
           <li><a href="/#choose-us-top">Why us?</a></li>
           <li><a href="/#feature-listing">Featured Listings</a></li>
         </ul>
      </li>
      
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" roll="button"aria-haspopup="true" aria-expanded="false">Real Estate<span class="caret"></span></a>        
        <ul class="dropdown-menu">
          <li class ="hvr-underline-reveal"><%= link_to "Housing Analytics", charts_path %></li>
          <li class ="hvr-underline-reveal"><%= link_to "Vendors", vendors_path %></li>           
         </ul>
      </li>
      <li class ="hvr-underline-reveal"><a href="#" id="bookmark-btn">Bookmarks</a></li>
      
     <% if user_signed_in? %>
        <li class ="hvr-underline-reveal"><%= link_to "New Listing", new_listing_path %></li>
        <li class="hvr-underline-reveal"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
     <% else %>
        <li class="hvr-underline-reveal"><%= link_to "Log in", new_user_session_path%></a></li>
        <li class="hvr-underline-reveal"><%= link_to "Sign up", new_user_registration_path%></a></li> 
    <% end %>  
      <% if user_signed_in? %>
      <li class="dropdown">
       <a href="#" class="dropdown-toggle" data-toggle="dropdown" roll="button"aria-haspopup="true" aria-expanded="false"><%= User.find(current_user.id).firstname %> <span class="caret"></span></a>   
        <ul class="dropdown-menu">
          <li><%= link_to "Edit Profile", user_path(current_user.id) %></li>
         </ul>
      </li>
    <% end %>
      
    </ul>
  </div>
</section>

app/views/listings/basic.html.erb
<div class="col-md-12 col-sm-12 col-xs-12" id="head-top"> <!-- form-head grid -->
  <div class="form-head-left">
  <br>
  <br>
  <p><span id="address-title"></span></p>
  </div>
  <div class="form-head">
    <h4 class="form-header" id="basic-upload-header">Upload Photos</h4>
  </div>
</div> <!-- end form-head grid -->

<div class="col-md-3 col-sm-3 col-xs-12"> <!-- sidebar grid -->
  <div class="side-bar">
  <div id="detaildiv"><i class="fa fa-wpforms fa-2x" aria-hidden="true"></i><br>  <% if @listing.user == current_user %>
    <%= link_to 'Edit Listing', edit_listing_path(@listing), class:"side-nav-a" %> 
  <% end %> </div>
  <div id="detaildiv"><a class="side-nav-a" id="detail-side-click" href="#"><i class="fa fa-wpforms fa-2x" aria-hidden="true"></i><br> Details </a></div>
   <div id="amenitydiv"><a class="side-nav-a" id="amenity-side-click" href="#"><i class="fa fa-ellipsis-v fa-2x" aria-hidden="true"></i><br> Amenities </a></div>
   <div id="photodiv"><i class="fa fa-camera fa-2x" aria-hidden="true"></i><br> <%=link_to 'edit photos', listing_basic_path(@listing), class:"side-nav-a" %> </div>
   <div id="deletediv"><i class="fa fa-trash-o fa-2x" aria-hidden="true"></i><br> <%= link_to "Delete", listing_path(@listing),class:"side-nav-a", data: { confirm: "Are you sure?" },  method: :delete %></div>
  </div>

  </div>
</div> <!-- end sidebar grid -->     

<div class="col-md-9 col-sm-9 col-xs-12"><!--photo uploader-->
  <% if @listing.user == current_user %>
    <%= form_for(Image.new, html: { multipart: true, class: "dropzone", id:"listing-images"}) do |f|  %>
      <%= f.hidden_field :listing_id, value: @listing.id%>
      <div class="fallback">
        <%= f.file_field :image %><br>
        <%= f.submit "Upload my image" %>
      </div>
    <% end %>
  <% end %>
</div>
<!--end photo uploader-->

<!--photo output-->
<!-- <div id="upload_photos_basic"> -->
  <% @listing.images.each do |image| %>
    <div class="upload_photos_box">
      <div class="col-md-4 col-sm-4 col-xs-12">
        <!-- <div class="img-thumbnail"> -->
          <%= image_tag image.image.url(:medium), alt: image.image.url(:thumb) %>
          <%= link_to "Delete", image, method: :delete %>
        <!-- </div> -->
      </div>
    </div>
  <% end %>
<!-- </div> -->

<!--photo output-->
<div class="row">

  <div class="col-md-4 col-sm-4 col-xs-12" >
      <button id="submit-listing" class="btn btn-default"><%= link_to 'Submit Listing', listing_path(@listing)%></button>
    </div>
</div>

app/views/listings/edit.html.erb
<div class="row">
<div class="col-md-12 col-sm-12 col-xs-12" id="head-top"> <!-- form-head grid -->
  <div class="form-head-left">
  <br>
  <br>
  <p><span id="address-title"></span></p>
  </div>
  <div class="form-head">
    <h4 class="form-header">Edit Listing Details</h4>
  </div>
</div> <!-- end form-head grid -->

<div class="col-md-3 col-sm-3 col-xs-12"> <!-- sidebar grid -->
  <div class="side-bar">
   <div id="basicdiv" class="side-nav-clicked"><a  class="side-nav-a" id="basic-side-click" href="#"><i class="fa fa-home fa-2x" aria-hidden="true"></i><br> Basic </a></div>
   <div id="detaildiv"><a class="side-nav-a" id="detail-side-click" href="#"><i class="fa fa-wpforms fa-2x" aria-hidden="true"></i><br> Details </a></div>
   <div id="amenitydiv"><a class="side-nav-a" id="amenity-side-click" href="#"><i class="fa fa-ellipsis-v fa-2x" aria-hidden="true"></i><br> Amenities </a></div>
   <div id="photodiv"><i class="fa fa-camera fa-2x" aria-hidden="true"></i><br> <%=link_to 'edit photos', listing_basic_path(@listing), class:"side-nav-a" %> </div>
   <div id="deletediv"><i class="fa fa-trash-o fa-2x" aria-hidden="true"></i><br> <%= link_to "Delete", listing_path(@listing),class:"side-nav-a", data: { confirm: "Are you sure?" },  method: :delete %></div>
  </div>
</div> <!-- end sidebar grid -->
<div class="col-md-8 col-sm-8 col-xs-12"> <!-- form content grid -->
    <%= render 'form' %>
</div> <!-- end form content grid -->


</div> <!-- row -->

app/views/listings/index.html.erb
<%= render 'layouts/header' %>
<%= render 'layouts/bookmarkRightBar' %>




  <h2 class="listing-heading">Listings</h2>

  <% if @listings.empty? %>
    <div class="jumbotron">
      <h3 class="alert-message-head">No matching results found. All listings shown.</h3>
      <% @listings = Listing.page(params[:page]).per(12).order(created_at: :desc) %>
  <% end %>
     <%= render 'layouts/search' %>
    </div>

<!-- Listing Box Begins -->
<div class="row listing">
  <% @listings.each_with_index do |listing, index| %>
    <div class=" listing-box col-md-4 col-sm-4 cols-xs-12 ">
      <div class="featureList text-center">
        <div id="carousel-listing-<%= index+1 %>" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <% listing.images.each_with_index do |image, index| %>
            <div class=
              <% if index==0 %> "item active" <% else %> "item" <% end %>
            >
             <%= image_tag(image.image.url(:large), alt: image.image.url(:thumb)) %>
            </div>
            <% end %>      
          </div>
          <a class="left carousel-control c-control" href="#carousel-listing-<%= index+1 %>" role="button" data-slide="prev">
            <span class="icon-prev" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control c-control" href="#carousel-listing-<%= index+1 %>" role="button" data-slide="next">
            <span class="icon-next" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
          <div class="listing-box-info">
            <h4 class="regular property-price">$<%= link_to to_currency(listing.price), listing %></h4>
            <div class="feature-short-info">
              <p class="address"><%= listing.address %></p>
              <p>
                <span class="bedroom"><%= listing.bedrooms %> Bedrooms</span>
                <span class="bathroom"><%= listing.bathrooms %> Bathrooms</span>
                <span class="size"><%= to_currency(listing.size) %> sq ft</span>
                <%= link_to '<i class="fa fa-bookmark-o" aria-hidden="true"></i>'.html_safe,listing_add_bookmark_path(:listing_id=>listing.id), 'data-method' => 'post', 'data-remote' => 'true', 'data-type' => 'json', 'class' => 'bookmark' %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<!-- Listing Box Ends -->

<div id="page_number">  <%= paginate @listings %> </div>
<%= render 'layouts/footer' %>

app/views/listings/new.html.erb
<section class="overlay nav navbar">

<img id="nav-logo" src="/assets/unlisted-logo.png" />

  <p class="icon">&#9776;</p>
  <div class="navbar-collapse collapse navbar-right">
    <ul class="nav navbar-nav">

     <li class="dropdown">
       <a href="#" class="dropdown-toggle" data-toggle="dropdown" roll="button"aria-haspopup="true" aria-expanded="false">Home <span class="caret"></span></a>        
        <ul class="dropdown-menu">
          <li><a href="/">Home</a></li>
         </ul>
      </li>

      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" roll="button"aria-haspopup="true" aria-expanded="false">Real Estate<span class="caret"></span></a>        
        <ul class="dropdown-menu">
          <li class ="hvr-underline-reveal"><%= link_to "Housing Analytics", charts_path %></li>
          <li class ="hvr-underline-reveal"><%= link_to "Vendors", vendors_path %></li>           
         </ul>
      </li>
      
     <% if user_signed_in? %>
        <li class ="hvr-underline-reveal"><%= link_to "New Listing", new_listing_path %></li>
        <li class="hvr-underline-reveal"><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
     <% else %>
        <li class="hvr-underline-reveal"><%= link_to "Log in", new_user_session_path%></a></li>
        <li class="hvr-underline-reveal"><%= link_to "Sign up", new_user_registration_path%></a></li> 
    <% end %>  
      <% if user_signed_in? %>
      <li class="hvr-underline-reveal"><a><%= User.find(current_user.id).firstname %></a></li>
      <% end %>
      
    </ul>
  </div>
</section>


<div class="row">
<div class="col-md-12 col-sm-12 col-xs-12" id="head-top"> <!-- form-head grid -->
  <div class="form-head-left">
  <br>
  <br>
  <p><span id="address-title"></span></p>
  </div>
  <div class="form-head">
    <h4 class="form-header">Listing Details</h4>

  </div>
</div> <!-- end form-head grid -->

<div class="col-md-3 col-sm-3 col-xs-12"> <!-- sidebar grid -->
  <div class="side-bar">
   <div id="basicdiv" class="side-nav-clicked"><a  class="side-nav-a" id="basic-side-click" href="#"><i class="fa fa-home fa-2x" aria-hidden="true"></i><br> Basic Details</a></div>
   <div id="detaildiv"><a class="side-nav-a" id="detail-side-click" href="#"><i class="fa fa-wpforms fa-2x" aria-hidden="true"></i><br> Property Details </a></div>
   <div id="amenitydiv"><a class="side-nav-a" id="amenity-side-click" href="#"><i class="fa fa-ellipsis-v fa-2x" aria-hidden="true"></i><br> Amenities </a></div>
  
  </div>
</div> <!-- end sidebar grid -->

<div class="col-md-9 col-sm-9 col-xs-12"> <!-- form content grid -->
    <%= render 'form' %>
</div> <!-- end form content grid -->


</div> <!-- row -->

app/views/users/show.html.erb
<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <!-- nav start -->


      <div class="profile-nav-wrap">
        <section class="overlay nav navbar">
          <img id="nav-logo" src="/assets/unlisted-logo.png">

          <div class="navbar-collapse collapse navbar-right">
            <ul class="nav navbar-nav">
              <li class="dropdown">
                <a aria-expanded="false" aria-haspopup="true" class=
                "dropdown-toggle" data-toggle="dropdown" href="#">Home
                <span class="caret"></span></a>

                <ul class="dropdown-menu">
                  <li>
                    <a href="/">Home</a>
                  </li>


                  <li>
                    <a href="#choose-us-top">Why us?</a>
                  </li>


                  <li>
                    <a href="#feature-listing">Featured Listings</a>
                  </li>
                </ul>
              </li>


              <li class="dropdown">
                <a aria-expanded="false" aria-haspopup="true" class=
                "dropdown-toggle" data-toggle="dropdown" href="#">Real
                Estate<span class="caret"></span></a>

                <ul class="dropdown-menu">
                  <li class="hvr-underline-reveal">
                  <%= link_to "Housing Analytics", charts_path %>
                  </li>


                  <li class="hvr-underline-reveal">
                  <%= link_to "Vendors", vendors_path %>
                  </li>
                </ul>
              </li>


              <li class="hvr-underline-reveal">
                <a href="#" id="bookmark-btn">Bookmarks</a>
              </li>
              <%if user_signed_in? %>

              <li class="hvr-underline-reveal">
              <%= link_to "New Listing", new_listing_path %>
              </li>


              <li class="hvr-underline-reveal">
              <%= link_to "Log out", destroy_user_session_path, method: :delete %>
              </li>
              <%else %>

              <li class="hvr-underline-reveal">
              <%= link_to "Log in", new_user_session_path%>
              </li>


              <li class="hvr-underline-reveal">
              <%= link_to "Sign up", new_user_registration_path%>
              </li>
              <%end %><%if user_signed_in? %>

              <li class="hvr-underline-reveal">
                <a><%= User.find(current_user.id).firstname %></a>
              </li>
              <%end %>
            </ul>
          </div>
        </section>
      </div>
      <!--  end profile-nav-wrap -->
    </div>
    <!-- nav end -->


    <div class="col-md-12 col-sm-12 col-xs-12">
      <!-- profile nav start -->
      <!--   <div class="profile-nav">
      <h1>Profile</h1>
    </div> -->
    </div>
    <!-- profilenav end -->


    <div class="col-md-12 col-sm-12 col-xs-12">
      <!-- profile jumbo start -->


    <!--   <div class="jumbotron" id="profile-jumbotron">
      </div> -->
    </div>
    <!-- profile jumbo end -->


    <div class="col-md-3 col-sm-3 col-xs-12 no-padding-profile">
      <!-- profile-side-nav -->


      <div id="profile-side-nav-wrap">
        <div id="user-profile-name">
          <h2><%=User.find(current_user.id).firstname %></h2></div><!-- end user profile name -->

        <div id="profile-nav-home">
          <a href="/"><i aria-hidden="true" class="fa fa-home fa-2x"></i><br>
          Home</a>
        </div>
        <!-- end profile-nav-home
 -->


        <div id="profile-nav-analytics">
          <a href="/charts"><i aria-hidden="true" class="fa fa-area-chart fa-2x"></i><br>
          Housing Analytics</a>
        </div>
        <!-- end house-nav-analytics -->

        <div id="profile-edit-user-side-nav">
        <a href="<%= edit_user_registration_path %>"><i class="fa fa-user fa-2x" aria-hidden="true"></i><br>Edit Profile</a>
        </div>
      </div>
      <!-- end profile-side-nav-wrap -->
    </div>
    <!--  end profile side nav -->


    <div class="col-md-9 col-sm-9 col-xs-12 ">
      <!-- main profile content -->


      <div id="main-content-wrap">
        <div class="container">
          <!-- container (for listings) -->


          <div class="profile-listing-wrap">
            <div id="listing-head-div">
              <h3>Your Listings</h3>
            </div>
            <!-- end listing-head-div -->


            <div id="profile-user-listing-div">
              
              <div id="profile-user-listing-img-wrap">
                 <div class="featureList text-center">
        <div id="carousel-listing-2" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            <div class="item active">
              <%= image_tag "listing_images/1.jpg", class: 'img-responsive' %>
            </div>
            <div class="item">
              <%= image_tag "listing_images/17.jpg", class: 'img-responsive' %>
            </div>
            <div class="item">
              <%= image_tag "listing_images/3.jpg", class: 'img-responsive' %>
            </div>
          </div>
          <a class="left carousel-control c-control" href="#carousel-listing-2" role="button" data-slide="prev">
            <span class="icon-prev" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control c-control" href="#carousel-listing-2" role="button" data-slide="next">
            <span class="icon-next" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
          <div class="listing-box-info">
            <h4 class="regular property-price">$2,456,783</h4>
            <div class="feature-short-info">
              <p class="address">123 Georgia St.</p>
              <p>
                <span class="bedroom">3 Bedrooms</span>
                <span class="bathroom">2 Bathrooms</span>
                <span class="size">2,214 sq ft</span>
              </p>
            </div>
          </div>
        </div>
      </div>
              </div>
              
              <div id="profile-listing-btn-wrap">
                <% current_user.listings.each do |listing| %>
                 <%= link_to "Edit", edit_listing_path(listing), id: "profile-edit-btn" %>
                 <%= link_to "Delete", listing_path(listing), id: "profile-delete-btn", method: :delete %>
                 <% end %>
              </div> <!-- end profile-listing-btn-wrap -->
            </div>
            <!-- end profile user listing div -->
          </div>
          <!-- end profile-listing-wrap -->
        </div>
        <!-- end container (for listings) -->
      </div>
    </div>
    <!-- end main profile content -->
  </div>
  <!--  row end -->